---
- name: Install Rubby
  hosts: all
  become: true
  tasks:

    - name: "APT: Install aptitude package"
      apt:
        name: aptitude
        force_apt_get: yes

    - name: "Update Cache"
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update & install
      apt:
        name: "{{ item }}"
        state: present
      loop:
         - ruby-full
         - ruby-bundler
         - build-essential
